### ISSUE TITLE
BSP reference model JSON-LD vocabulary doesn't import class properties in StarUML

### ISSUE THREAD

**Issue by mrtnmrtn** [gs-gs/staruml-cefact#142]
Using the latest version of the https://github.com/gs-gs/staruml-cefact plugin for StarUML 4.0.1 on Windows 10 to import the vocabulary at https://service.unece.org/trade/uncefact/vocabulary/unece/ imports the classes but not the class properties.

![image](https://user-images.githubusercontent.com/33596380/115205088-89fb7580-a13c-11eb-9f26-e1d3da40f478.png)

Using the vocabulary at https://edi3.org/vocabulary/unece/ does import the classes and their properties.

![image](https://user-images.githubusercontent.com/33596380/115205112-8e279300-a13c-11eb-86d6-bb348f9493c6.png)

Can you please investigate?

**Comment by nissimsan** [comment]
Hi @mrtnmrtn ,
I don't see the problem. Are accountingDocumentSetTriggerCode, ammountTypeCode, etc not properties of the AccountingAccount class (ref. your screenshot)? 
Nis

**Comment by kshychko** [comment]
Hi @mrtnmrtn ! I've fixed the processing issue, it was caused due to a change of the UNCL enumeration names - we treat them specially. Also, I added UN/CEFCAT menu under JSON-LD tool with two items:
1. Import UN/CEFACT Vocabulary - it will download and process the vocabulary from https://service.unece.org/trade/uncefact/vocabulary/uncefact.jsonld
2. Init UN/EDIFACT Consolidated Code Lists (UNCL) - allows to add values to enumerations from UNCL package. We don't load them by default as they are pretty heavy and not all of them might be needed.

Please update the extension using "Install from URL" button under the extension manager. After the update, you should see the JSON-LD (v0.7.0-rc2) menu item.

**Comment by kshychko** [comment]
> Hi @mrtnmrtn ,
> I don't see the problem. Are accountingDocumentSetTriggerCode, ammountTypeCode, etc not properties of the AccountingAccount class (ref. your screenshot)?
> Nis

@nis, the problem was with the UN/EDIFACT code lists, they were treated as usual classes when should be considered as enumerations and created in a separate package.

If you get a chance to test new UN/CEFACT menu items and provide your feedback that would be great!

**Comment by mrtnmrtn** [comment]
Thanks @kshychko - I've just done a quick test and it looks good. All the class attributes seem to appear and the code lists I've tried to import have worked.
